# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Herminio García | Personal webpage
email: herminiogg@outlook.com
description: Herminio García personal webpage. I am a Web and Software Engineering.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://herminiogarcia.com" # the base hostname & protocol for your site
twitter_username: herminio_gg
github_username:  herminiogg

# Build settings
markdown: kramdown


# Author Details
author: 'Herminio García González'

permalink: /blog/:year/:month/:day/:title/


# translation
t:
  en:
    title-name: Herminio García
    title-url: "/"
    description: Herminio García personal webpage. PhD student in Computer Science at University of Oviedo.
    blog-name: Blog
    blog-url: "/blog"
    hobbies: Hobbies
    hobbies-url: "#photography"
    hobbies-section: "photography"
    projects: Projects
    projects-url: "#projects"
    projects-section: projects
    who-am-i: Who am I?
    who-am-i-url: "#who-am-i"
    who-am-i-section: "who-am-i"
    name: Herminio García González
    description: PhD student in Computer Science at University of Oviedo
    who-am-i-text: I am a PhD student at the University of Oviedo. I obtained my MSc in Web Engineering by the University of Oviedo in 2016 and I also have a Bachelor Degree in Software Engineering by the same university. My current research interests are Web Semantics, e-Learning and Big Data.
    contact-me: Contact me
    projects-text: During my PhD I am working in various projects like XMLSchema2ShEx and ShExML. Feel free to visit my Github to see in what I am working at this moment.
    linkedin: linkedin
    github: github
    photography: Photography
    photography-text: When I have free time I take my camera to relax. Feel free to visit my Flickr.
    flickr: Flickr
    min-read: min read
    research: Research
    research-url: "/research"
    phd-url: "/thesis"
    phd-name: PhD Thesis
  es:
    title-name: Herminio García
    title-url: "/es"
    description: Página web personal de Herminio García, estudiante del doctorado en Ingeniería Informática en la Universidad de Oviedo.
    blog-name: Blog
    blog-url: "/es/blog"
    title: Herminio García
    blog: Blog
    hobbies: Aficiones
    hobbies-url: "/es/#fotografia"
    hobbies-section: "fotografia"
    projects: Proyectos
    projects-url: "/es/#proyectos"
    projects-section: proyectos
    who-am-i: ¿Quién soy?
    who-am-i-url: "/es/#quien-soy"
    who-am-i-section: "quien-soy"
    name: Herminio García González
    description: Estudiante del doctorado en Ingeniería Informática de la Universidad de Oviedo
    who-am-i-text: Soy un estudiante de doctorado de la Universidad de Oviedo. Obtuve mi Máster en Ingeniería Web por la Universidad de Oviedo en 2016. También soy Ingeniero Informático del Software por la misma universidad. Mi areas de investigación de interes son la Web Semántica, e-Learning y Big Data.
    contact-me: Contactar
    projects-text: Durante mi tesis doctoral estoy trabajando en varios proyectos entre los cuales se encuentran XMLSchema2ShEx y ShExML. Visita mi cuenta de Github para saber en qué estoy trabajando ahora mismo.
    linkedin: linkedin
    github: github
    photography: Fotografía
    photography-text: Cuando tengo tiempo libre me gusta coger mi cámara para relajar. Siéntete libre de visitar mi Flickr.
    flickr: Flickr
    min-read: minutos de lectura
    research: Investigación
    research-url: "/es/research"
    phd-url: "/es/thesis"
    phd-name: Tesis doctoral

defaults:
    scope:
      path: _posts/en
    values:
      layout: post
      lang: en
    scope:
      path: _posts/es
    values:
      layout: post
      lang: es
