# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Herminio García | Personal webpage
email: herminiogg@outlook.com
description: Herminio García personal webpage. PhD in Computer Science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://herminiogarcia.com" # the base hostname & protocol for your site
twitter_username: herminio_gg
github_username:  herminiogg

# Build settings
markdown: kramdown


# Author Details
author: 'Herminio García González'

permalink: /blog/:year/:month/:day/:title/


# translation
t:
  en:
    title-name: Herminio García
    title-url: "/"
    description: Herminio García personal webpage. PhD in Computer Science.
    blog-name: Blog
    blog-url: "/blog"
    talks-name: Talks & Dissemination
    talks-url: "/talks"
    hobbies: Hobbies
    hobbies-url: "#photography"
    hobbies-section: "photography"
    projects: Projects
    projects-url: "#projects"
    projects-section: projects
    who-am-i: Who am I?
    who-am-i-url: "#who-am-i"
    who-am-i-section: "who-am-i"
    name: Herminio García González, PhD
    description: Data integration specialist at Kazerne Dossin
    who-am-i-text: "I am a data integration specialist at Kazerne Dossin, Belgium. I hold a PhD in Computer Science, a MSc in Web Engineering and a Bachelor's Degree in Software Engineering all by the University of Oviedo. My current research interests are: Semantic Web, data integration, data validation, Knowledge Graphs and Digital Humanities."
    contact-me: Contact me
    projects-text: I have developed various open source projects like XMLSchema2ShEx and ShExML. Feel free to visit my Github to see in what I am working at this moment.
    linkedin: linkedin
    github: github
    photography: Photography
    photography-text: When I have free time I take my camera to relax. Feel free to visit my Flickr.
    flickr: Flickr
    min-read: min read
    research: Research
    research-url: "/research"
    phd-url: "/thesis"
    phd-name: PhD Thesis
    cv: See my CV
    cv-url: /cv/CV-Herminio-Garcia-Gonzalez.pdf
  es:
    title-name: Herminio García
    title-url: "/es"
    description: Página web personal de Herminio García, Doctor en Informática por la Universidad de Oviedo.
    blog-name: Blog
    blog-url: "/es/blog"
    talks-name: Charlas y Divulgación
    talks-url: "/es/talks"
    title: Herminio García
    blog: Blog
    hobbies: Aficiones
    hobbies-url: "/es/#fotografia"
    hobbies-section: "fotografia"
    projects: Proyectos
    projects-url: "/es/#proyectos"
    projects-section: proyectos
    who-am-i: ¿Quién soy?
    who-am-i-url: "/es/#quien-soy"
    who-am-i-section: "quien-soy"
    name: Dr. Herminio García González
    description: Especialista en integración de datos en Kazerne Dossin
    who-am-i-text: Ahora mismo trabajo como especialista en integración de datos en Kazerne Dossin, Bélgica. Soy Doctor en Informática por la de Universidad de Oviedo, Máster en Ingeniería Web e Ingeniero Informático del Software por la misma universidad. Mi areas de investigación de interés son la Web Semántica, la integración y validación de datos, los grafos de conocimiento y las humanidades digitales.
    contact-me: Contactar
    projects-text: He desarrollado varios proyectos de código abierto entre los cuales se encuentran XMLSchema2ShEx y ShExML. Visita mi cuenta de Github para saber en qué estoy trabajando ahora mismo.
    linkedin: linkedin
    github: github
    photography: Fotografía
    photography-text: Cuando tengo tiempo libre me gusta coger mi cámara para relajar. Siéntete libre de visitar mi Flickr.
    flickr: Flickr
    min-read: minutos de lectura
    research: Investigación
    research-url: "/es/research"
    phd-url: "/es/thesis"
    phd-name: Tesis doctoral
    cv: Ver mi CV
    cv-url: /../cv/CV-Herminio-Garcia-Gonzalez.pdf

defaults:
    scope:
      path: _posts/en
    values:
      layout: post
      lang: en
    scope:
      path: _posts/es
    values:
      layout: post
      lang: es
